### ISSUE TITLE
Unable to resolve host

### ISSUE THREAD

**Issue by bernzJ** [milanmk/actions-file-deployer#1]
Hi, does this work with ips? I added my server's ip and I get an error, here is the log and my yaml config:

**Error:**
```
Unknown command `3m9QFPN_EDPjQ@***'.
Transfer files
  Synchronization: full
  Local path: .
  Remote path: /somepath
  Protocol: SFTP
  __________________________________________________
  mirror: Fatal error: max-retries exceeded (Could not resolve hostname ***: Temporary failure in name resolution)
  Error: Process completed with exit code 1.
```

**Yaml:**
```yaml
name: Deploy Files

on: push

jobs:
  master:
    name: master
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: "sftp"
          remote-host: ${{ secrets.FTP_SERVER }}
          remote-user: ${{ secrets.FTP_USERNAME }}
          remote-password: ${{ secrets.FTP_PASSWORD }}
          remote-port: 22
          remote-path: "/somepath"
```
