### ISSUE TITLE
Error "Git repository not found" with files in repository

### ISSUE THREAD

**Issue by AlexWestergaard** [milanmk/actions-file-deployer#11]
I receive the following error:
`Error: Git repository not found. Please ensure you have a checkout step before this step.`

But I have a repository and files in it:
```yml
jobs:
  deploy-queue:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Queue"
        uses: actions/checkout@v3
        with:
          path: "public_queue/**"
          fetch-depth: 0
      - name: "Checkout Shared"
        uses: actions/checkout@v3
        with:
          path: "shared/**"
          fetch-depth: 0
      - name: "Log Structure"
        run: |
          pwd
          tree
      - name: "Deploy Files"
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: "sftp"
          remote-host: ${{ secrets.SSH_QUEUE_HOST }}
          remote-user: ${{ secrets.SSH_QUEUE_USERNAME }}
          remote-password: ${{ secrets.SSH_QUEUE_PASSWORD }}
          ssh-private-key: ${{ secrets.SSH_QUEUE_PRIVATE_KEY }}
          remote-path: ${{ secrets.SSH_QUEUE_REMOTE_PATH }}
          sync: "full"
```

I can not figure out what the error refers to more specific. Hope you can help
