### ISSUE TITLE
sync: "delta" shows in logs success but not uploading latest version of the file

### ISSUE THREAD

**Issue by ikkitaguchi** [milanmk/actions-file-deployer#13]
Hi,

Could you please take a look a look? I'm using below parameters, and when I use sync: "delta" the latest files are not being uploaded, though shown in logs that file was uploaded. When I use sync: "full" - the all works fine as expected. 

```
jobs:

  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SFTP Deploy
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: "sftp"
          remote-host: ""
          remote-user: ""
          remote-password: ""
          remote-path: "/wp-content/themes/mytheme"
          local-path: "./wp-content/themes/mytheme"
          sync: "delta"
```

**Comment by ikkitaguchi** [comment]
By the way I tried about 5 other alternatives and this action is the best option as it shows needed level of debug, has clear parameters and just works - thanks for the development on this one!

**Comment by milanmk** [comment]
Could you please share the action log where files not uploaded.

**Comment by AlexWestergaard** [comment]
I have done a full sync and then afterwards changing files none are uploaded or deleted using the Delta

```yml
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SFTP
        uses: milanmk/actions-file-deployer@1.11
        with:
          remote-host: ${{ secrets.HOST }}
          remote-port: 22
          remote-user: ${{ secrets.HOST_USER }}
          remote-password: ${{ secrets.HOST_PASS }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE }}
          remote-path: "XXX"
          sync-delta-excludes: ".github/,tests/,.env"
```

```sh
Configurations
  File created: /home/runner/.ssh/config
  ____________________________________________________________________________________________________
  File created: /home/runner/.netrc
  ____________________________________________________________________________________________________
  File created: /home/runner/ssh_private_key
  ____________________________________________________________________________________________________
  File created: ~/.lftprc
Prepare files
  Event: push
  Revision: https://github.com/AlexWestergaard/felixity-net/commit/5470403c60ee21c410df237072fd29c9ab71fa55
  Committer: AlexWestergaard
  Message: Add GoFundMe badge
  ____________________________________________________________________________________________________
  File created: .deploy-revision
  5470403c60ee21c410df237072fd29c9ab71fa55
  ____________________________________________________________________________________________________
  Previous Revision: https://github.com/AlexWestergaard/felixity-net/commit/bfff7b8c773d47664e8bc7e2bdcdc817c5d77f39
  ____________________________________________________________________________________________________
  fatal: .github/,tests/,.env: no such path in the working tree.
  Use 'git <command> -- <path>...' to specify paths that do not exist locally.
  fatal: .github/,tests/,.env: no such path in the working tree.
  Use 'git <command> -- <path>...' to specify paths that do not exist locally.
Transfer files
  Protocol: sftp
  Synchronization: delta
  Local path: .
  Remote path: /var/www/***/laravel
  Upload files: 0
  Delete files: 0
  ____________________________________________________________________________________________________
  /home/runner/work/felixity-net/felixity-net/.deploy-running -> sftp://***@***:22/var/www/***/laravel/.deploy-running 0-0 
  /home/runner/work/felixity-net/felixity-net/.deploy-revision -> sftp://***@***:22/var/www/***/laravel/.deploy-revision 0-41 129 B/s
Cleanup
  removed '/home/runner/.netrc'
  removed '/home/runner/ssh_private_key'
  removed '/home/runner/transfer_log.txt'
Run actions/upload-artifact@v2
  with:
    name: transfer_artifacts
    path: ~/transfer_log.txt
  ~/transfer_files
  
    if-no-files-found: ignore
Multiple search paths detected. Calculating the least common ancestor of all paths
The least common ancestor is /home/runner. This will be the root directory of the artifact
```

I added some code to PHP File and deleted a another .PHP file, neither was updated or deleted.
