### ISSUE TITLE
can't upload files or folders into path with special characters like [ ]

### ISSUE THREAD

**Issue by ahcenezdh** [milanmk/actions-file-deployer#17]
Hey, when i'm trying to commit files into folders with special characters
i've got this 
```
  mput: resources/[standalone]/[phone]/lb-phone_prop/.fxap: no files found
  mput: resources/[standalone]/[phone]/lb-phone_prop/fxmanifest.lua: no files found
  mput: resources/[standalone]/[phone]/lb-phone_prop/stream/lb_phone_prop.ydr: no files found
  mput: resources/[standalone]/[phone]/lb-phone_prop/stream/lbphone_props.ytyp: no files found
```
here is my workflow
```yaml
name: 🚀 Développement - Star'Island
on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Deploy to SFTP
        uses: milanmk/actions-file-deployer@1.12
        with:
          remote-protocol: sftp
          remote-host: ${{ secrets.SFTP_HOST }}
          remote-port: 2022
          remote-user: ${{ secrets.SFTP_DEV_USER }}
          remote-password: ${{ secrets.SFTP_PASSWORD }}
          local-path: ./
          remote-path: /
          sync: delta
          debug: true
```
