### ISSUE TITLE
When I add a build step and it generates dist files, these are not uploaded with delta settings. 

### ISSUE THREAD

**Issue by shishirraven** [milanmk/actions-file-deployer#41]
First of all this is the best action I have found so far, especially because of the delta option it is great. 

The following is my workflow. 

```
on: push
name: 🚀 Deploy on on teampro New new
jobs:
  deploy-master:
    name: "Deploy on on teampro New new "
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔨 Build Project
        run: |
          cd todo/teamprotodo_vue/
          npm install
          npm run build
      - name: Deploy Files
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: "sftp"
          remote-host: ${{ secrets.DEPLOY_HOST }}
          remote-user: ${{ secrets.DEPLOY_USER }}
          ssh-private-key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          remote-path: "/home/bitnami/htdocs/teampro/new2"
```

You will notice I have added a build step. 
But the files which are generated from the build are not uploaded probably due to the fact that it finds the difference or changed files later. 

Is there a provision for this which I might of missed, if so please guide me. 
I need to upload todo/teamprotodo_vue/dist whenever the project is built. 

Thanks for the library, Have a nice day.
